image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    
before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

tailwind_build: 
  stage: build
  script: 
    - npm install --progress=false
    - npx tailwind build src/assets/styles.css -o src/dist/main.css
  artifacts:
    expire_in: 3 days
    paths: 
      - node_modules

deploy:
    stage: deploy
    script:
      - sshpass -V
      - export SSHPASS=$IIENS_PASSWD
      - sshpass -e scp -o StrictHostKeyChecking=no -r ./src/* magadeva2011@tom.iiens.net:~/html/portfolio
      - echo "Deployment complete"
    # specify environment this job is using
    environment:
      name: production
      url: http://magadeva.iiens.net/portfolio
    # only run on these branches
    only:
      - master
      - MVP